services:
  ros-autonomy:
    image: wisniax/ros-rover-base:autonomy-latest
    stdin_open: true
    container_name: ros-autonomy
    hostname: ros-autonomy
    tty: true
    pid: "host"
    ipc: "host"
    init: true
    network_mode: host
    environment:
      - TZ=Europe/Warsaw
      # Override for default ssh port (22)
      - SSH_PORT=3022 
    volumes:
      - type: bind
        source: ./
        target: /mnt/local
        bind:
          create_host_path: true
      - type: bind
        source: /dev/shm
        target: /dev/shm
    restart: unless-stopped