#!/bin/bash

drone_help() {
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  RAPTORS DRONE - Development Environment Command Reference"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "━━━━ STARTUP ━━━━"
    echo "  start_minimal    - Launch MAVROS only"
    echo "  start_hardware   - Connect to real flight controller"
    echo "  start_gazebo     - Launch Gazebo only"
    echo "  start_ardupilot  - Launch ArduPilot SITL only"
    echo "  start_mavros     - Launch MAVROS only"
    echo "  start_qgc        - Launch QGroundControl" 
    echo ""
    echo "  stop_gazebo / stop_ardupilot / stop_mavros - Stop specific"
    echo "  restart_mavros / restart_gazebo / restart_ardupilot - Restart specific component"
    echo ""
    echo "━━━━ BASIC CONTROL ━━━━"
    echo "  arm / disarm     - Arm/disarm motors"
    echo "  takeoff <alt>    - Takeoff to altitude (meters)"
    echo "  start_qgc        - Launch QGroundControl" 
    echo "  land             - Land the drone"
    echo "  STOP             - Emergency stop (kills motors)"
    echo ""
    echo "━━━━ FLIGHT MODES ━━━━"
    echo "  guided           - GUIDED mode (for waypoint navigation)"
    echo "  stabilize        - STABILIZE mode (manual flight)"
    echo "  loiter           - LOITER mode (hold position)"
    echo "  rtl              - Return to launch"
    echo "  auto             - AUTO mode (follow mission)"
    echo "  althold          - ALT_HOLD (hold altitude)"
    echo "  poshold          - POS_HOLD (hold position)"
    echo ""
    echo "━━━━ DIRECTIONAL MOVEMENT (GUIDED mode) ━━━━"
    echo "  forward [speed]  - Move forward (default: 1.0 m/s)"
    echo "  backward [speed] - Move backward (default: 1.0 m/s)"
    echo "  left [speed]     - Strafe left (default: 1.0 m/s)"
    echo "  right [speed]    - Strafe right (default: 1.0 m/s)"
    echo "  up [speed]       - Climb (default: 0.5 m/s)"
    echo "  down [speed]     - Descend (default: 0.5 m/s)"
    echo ""
    echo "  Examples:"
    echo "    forward 2      - Move forward at 2 m/s"
    echo "    up 0.3         - Climb slowly at 0.3 m/s"
    echo ""
    echo "━━━━ ROTATION ━━━━"
    echo "  yaw_left [rate]  - Rotate left (default: 0.5 rad/s)"
    echo "  yaw_right [rate] - Rotate right (default: 0.5 rad/s)"
    echo "  yaw_stop         - Stop rotation"
    echo ""
    echo "━━━━ VELOCITY CONTROL ━━━━"
    echo "  vel_linear <x> <y> <z>  - Set linear velocity only"
    echo "  vel <lx> <ly> <lz> <ax> <ay> <az> - Full 6DOF velocity"
    echo "  vel_stop                 - Stop all velocity commands"
    echo "  move_timed <x> <y> <z> <sec> - Move for specified duration"
    echo "  slow_stop                - Gradually decelerate to stop"
    echo ""
    echo "  Examples:"
    echo "    vel_linear 1 0.5 0.2  - Move forward+left+up simultaneously"
    echo "    vel 1 0 0 0 0 0.5     - Move forward while rotating"
    echo "    move_timed 2 0 0 10   - Move forward at 2 m/s for 10 seconds"
    echo ""
    echo "━━━━ MONITORING ━━━━"
    echo "  status           - Full status report"
    echo "  state            - Show flight mode and armed status"
    echo "  pos              - Show GPS position"
    echo "  battery          - Show battery status"
    echo "  topics           - List all MAVROS topics"
    echo "  nodes            - List active ROS2 nodes"
    echo "  check_connection - Verify MAVROS connection"
    echo ""
    echo "━━━━ NAVIGATION ━━━━"
    echo "  goto <lat> <lon> [alt] - Navigate to GPS coordinate"
    echo "  clear_mission    - Clear all waypoints"
    echo "  Example:"
    echo "    goto 47.3977 8.5456 20  - Fly to coordinates at 20m altitude"
    echo ""
    echo ""
    echo "━━━━ PARAMETERS ━━━━"
    echo "  get_param <name> - Get parameter value"
    echo "  set_param <name> <val> - Set parameter"
    echo "  save_params      - Save parameters to EEPROM"
    echo ""
    echo "━━━━ DEVELOPMENT ━━━━"
    echo "  ws               - Go to workspace directory"
    echo "  build            - Build ROS2 workspace"
    echo "  rebuild          - Quick rebuild + source"
    echo "  clean_build      - Clean build from scratch"
    echo "  src              - Source workspace"
    echo "  new_package <name> - Create new ROS2 package"
    echo ""
    echo "━━━━ RECORDING ━━━━"
    echo "  record [name]    - Start recording bag file"
    echo "  playback <name>  - Play back recording"
    echo "  list_bags        - List all recordings"
    echo ""
    echo "━━━━ SAFETY ━━━━"
    echo "  disable_safety_checks  - Disable pre-arm checks"
    echo "  reenable_safety_checks - Re-enable safety checks"
    echo "  set_geofence <radius>  - Set geofence radius (meters)"
    echo ""
    echo "More information at: https://github.com/kienphamh/Raptors-drone-environment"
}

alias help='drone_help'
alias h='drone_help'

echo "Type 'help' to see all available commands"
echo ""