services:
  drone-sim:
    image: wisniax/ros-rover-base:drone-latest
    build: .
    container_name: raptors-drone-dev
    hostname: raptors-drone-dev
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    ipc: host
    pid: "host"
    init: true
    
    # X11 Forwarding
    environment:
      - PULSE_SERVER=tcp:127.0.0.1:4800
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - SSH_PORT=2222
    
    volumes:
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev/shm:/dev/shm

    group_add:
      - audio

    security_opt:
      - seccomp:unconfined
      
    # Intel/AMD GPU
    devices:
      - /dev/dri:/dev/dri
